source "http://gemcutter.org"

gem "rails", "3.0.1"

# ui
gem "haml"
gem 'compass', '0.10.6.pre.1'

# utils
gem 'magic', '~> 0.2.6'
gem 'ruby-stemmer', '~> 0.8.2'
gem 'magent', '~> 0.5.2'
gem 'uuidtools'
gem 'sanitize', '~> 1.2.1'

# mongodb
gem 'bson', '1.1.1'
gem 'bson_ext', '1.1.1'
gem 'plucky', '0.3.6'

gem 'mongo', '1.1.1'
gem 'jnunemaker-validatable', '1.8.4'
gem 'mongo_mapper', '0.8.6'
gem 'mongomapper_ext', '0.5.1'

# authentication
gem 'omniauth', '0.1.4'
gem 'multiauth', '0.2.7'

group :scripts do
  gem 'eventmachine', '~> 0.12.10'
  gem 'em-websocket', '~> 0.1.4'
  gem 'cronedit'
end

group :development do
  gem 'rspec', '2.0.0'
  gem 'rspec-rails', '2.0.0'
  gem 'mongrel', '1.2.0.pre2'
  gem 'nifty-generators', '~> 0.4.2'
  gem 'capistrano'
end
