source "http://gemcutter.org"

gem "rails", "3.0.3"

# ui
gem "haml"
gem 'compass', '0.10.6.pre.1'

# utils
gem 'magic', '~> 0.2.6'
gem 'ruby-stemmer', '~> 0.8.2'
gem 'magent', '~> 0.5.2'
gem 'uuidtools'
gem 'sanitize', '~> 1.2.1'
gem 'dynamic_form'
gem 'will_paginate', :git => 'git://github.com/mislav/will_paginate.git', :branch => "rails3"
gem 'rdiscount'

# twitter
gem "twitter-text", "1.1.8"
gem "twitter_oauth"

# mongodb
gem 'bson', '1.1.2'
gem 'bson_ext', '1.1.2'

gem 'mongo', '1.1.2'
gem 'mongoid', '2.0.0.beta.20'
gem 'mongoid_ext', :git => "git://github.com/dcu/mongoid_ext.git"

# authentication
gem 'omniauth', '~> 0.1.6'
gem 'multiauth', :git => "http://github.com/dcu/multiauth.git"

gem 'orm_adapter'
gem 'devise', :git => 'http://github.com/plataformatec/devise.git'


group :scripts do
  gem 'eventmachine', '~> 0.12.10'
  gem 'em-websocket', '~> 0.1.4'
  gem 'cronedit'
end

group :development do
  gem 'rspec', '2.0.0'
  gem 'rspec-rails', '2.0.0'
  gem 'mongrel', '1.2.0.pre2'
  gem 'nifty-generators', '~> 0.4.2'
  gem 'capistrano'
  gem "fabrication"
  gem "autotest"
  gem "remarkable_mongoid", ">= 0.5.0"
  gem 'hpricot'
  gem 'ruby_parser'
  gem "database_cleaner"

end

